Update patch set 6
Patch Set 6:

> Patch Set 6:
> 
> When trying to make a standalone build, bazel fails with an error:
> 
>   ERROR: error loading package '': Unable to load file '//tools/bzl:js.bzl': file doesn't exist
> 
> I can't see the difference with delete-project setup, and it works fine when building in-tree: any advice?

The tools/bzl/js.bzl file needs to be added to the project.  Also genrule2.bzl.

Patch-set: 6
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>